// Native-authored multilingual route SEO pack for secondary markets.
// These are authored per locale, not machine translations of the German pack.

const { pick } = require('./compose');

const LOCALES = {
  en: {
    overview: 'Route overview', price: 'Price and timing', airlines: 'Airlines and choice', direct: 'Direct flights and stops',
    airport: 'Airport details', plan: 'Planning the trip', faqPrice: 'What does the route cost?', faqDirect: 'Are there direct flights?', faqAirlines: 'Which airlines serve the route?', faqDuration: 'How long is the flight?',
    title: (c) => `${c.o} to ${c.d} flights: prices, airlines & flight time | Airpiv`,
    meta: (c) => `Compare ${c.o} to ${c.d} flights with real route data: fares, airlines, flight time and direct-flight options. Plan the route with clear, useful details.`,
    intro: (c) => `${c.o} to ${c.d} is a route where the best flight depends on what matters most: price, travel time, airline choice or a direct connection. This page brings the available route signals together so you can compare the practical options before booking.`,
    overviewBody: (c) => `${c.o} and ${c.d} are about ${c.km} km apart by air. The route is classified as ${c.haul}. ${c.fmtDur ? `Observed flight time is around ${c.fmtDur}. ` : ''}${c.airlineCount ? `${c.airlineCount} airlines have been observed on the route. ` : ''}Use these figures as a starting point and check the exact travel date before booking.`,
    priceBody: (c) => `${c.priceMin != null ? `Observed fares start at about ${Math.round(c.priceMin)} EUR` : 'Fare information is available for this route'}${c.priceMax && c.priceMax > c.priceMin ? ` and reach around ${Math.round(c.priceMax)} EUR` : ''}. ${c.priceTrend === 'up' ? 'Recent pricing has been trending upward, so waiting can be costly.' : c.priceTrend === 'down' ? 'Recent pricing has been trending downward, which can reward flexible travellers.' : 'Recent pricing has been comparatively stable.'} Prices are snapshots, so availability and final fare can change.`,
    airlinesBody: (c) => `${c.airlineCount || 'Several'} airlines are represented in the route data. More choice can mean different departure times, fare families and baggage rules. Compare the total trip cost and schedule rather than the headline fare alone.`,
    directBody: (c) => c.directB === 'all-direct' ? `All observed options are direct flights, so there is no connection to manage. That makes the route especially practical when arrival reliability matters.` : c.directB === 'connections-only' ? `The observed route data does not show a direct option. Allow extra time for the connection and check the airport and minimum connection time before booking.` : `Direct flights are available alongside connecting options. A direct ticket usually saves time, while a connection can widen the price and schedule choice.`,
    airportBody: (c) => `${c.o} departs through ${c.oIata || 'the origin airport'} and ${c.d} arrives through ${c.dIata || 'the destination airport'}. Check terminal, transfer and ground-transport details close to departure because airport procedures can vary by flight and date.`,
    planBody: (c) => `For a smoother trip, compare departure times, baggage rules, connection length and the total door-to-door journey. ${c.haul === 'long-haul' ? 'On a long-haul route, cabin comfort and connection quality can be as important as the fare.' : 'On a shorter route, airport access and convenient departure times can matter more than a small fare difference.'}`,
    faqPriceA: (c) => `Observed prices start at about ${c.priceMin != null ? Math.round(c.priceMin) : 'the currently available fare'} EUR, but the exact fare depends on date, availability and ticket conditions.`,
    faqDirectA: (c) => c.directB === 'all-direct' ? 'Yes. The observed route options are direct.' : c.directB === 'connections-only' ? 'No direct option is currently represented in the observed route data.' : 'Yes, direct options are represented, alongside connecting flights.',
    faqAirlinesA: (c) => `${c.airlineCount || 'Several'} airlines are represented in the available route data.`,
    faqDurationA: (c) => c.fmtDur ? `The observed average flight time is around ${c.fmtDur}. Actual elapsed travel time depends on the itinerary and connection.` : 'Flight time varies by itinerary and connection; check the selected flight for the exact schedule.'
  },
  fr: {
    overview: 'Vue d’ensemble du trajet', price: 'Prix et période de réservation', airlines: 'Compagnies aériennes', direct: 'Vols directs et escales', airport: 'Aéroports', plan: 'Bien préparer le voyage', faqPrice: 'Quel est le prix du trajet ?', faqDirect: 'Existe-t-il des vols directs ?', faqAirlines: 'Quelles compagnies desservent le trajet ?', faqDuration: 'Combien de temps dure le vol ?',
    title: (c) => `Vols ${c.o} → ${c.d} : prix, compagnies et durée | Airpiv`,
    meta: (c) => `Comparez les vols ${c.o}–${c.d} à partir de données réelles : prix, compagnies, durée et options sans escale. Préparez votre voyage efficacement.`,
    intro: (c) => `Pour voyager de ${c.o} à ${c.d}, le meilleur vol dépend du prix, de la durée, des horaires et du nombre d’options directes. Cette page rassemble les données disponibles sur le trajet pour comparer les choix importants avant de réserver.`,
    overviewBody: (c) => `${c.o} et ${c.d} sont séparées d’environ ${c.km} km à vol d’oiseau. Le trajet est classé ${c.haul}. ${c.fmtDur ? `La durée observée est d’environ ${c.fmtDur}. ` : ''}${c.airlineCount ? `${c.airlineCount} compagnies ont été observées. ` : ''}Vérifiez toujours la disponibilité exacte pour vos dates.`,
    priceBody: (c) => `Les tarifs observés commencent autour de ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR${c.priceMax && c.priceMax > c.priceMin ? ` et peuvent atteindre environ ${Math.round(c.priceMax)} EUR` : ''}. ${c.priceTrend === 'up' ? 'La tendance récente est à la hausse.' : c.priceTrend === 'down' ? 'La tendance récente est plutôt à la baisse.' : 'Les tarifs sont restés relativement stables récemment.'} Le prix final dépend de la date et des conditions du billet.`,
    airlinesBody: (c) => `${c.airlineCount || 'Plusieurs'} compagnies apparaissent dans les données du trajet. Comparez non seulement le tarif, mais aussi les horaires, les bagages et les conditions de modification.`,
    directBody: (c) => c.directB === 'all-direct' ? `Les options observées sont toutes sans escale. C’est un avantage important pour réduire le temps de voyage et les risques liés aux correspondances.` : c.directB === 'connections-only' ? `Aucune option directe n’apparaît actuellement dans les données observées. Prévoyez une marge suffisante pour la correspondance.` : `Des vols directs et des itinéraires avec correspondance sont disponibles. Le direct fait gagner du temps, tandis qu’une escale peut offrir davantage de choix tarifaires.`,
    airportBody: (c) => `${c.o} utilise ${c.oIata || 'son aéroport de départ'} et ${c.d} ${c.dIata || 'son aéroport d’arrivée'}. Vérifiez le terminal et les transferts avant le départ.`,
    planBody: (c) => `Pour comparer correctement, regardez le temps total, les bagages, les horaires et la durée des correspondances. ${c.haul === 'long-haul' ? 'Sur une longue distance, le confort et la qualité de la correspondance comptent particulièrement.' : 'Sur une distance plus courte, les horaires et l’accès aux aéroports peuvent peser plus qu’une petite différence de prix.'}`,
    faqPriceA: (c) => `Les tarifs observés commencent autour de ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR. Le prix exact varie selon la date et les disponibilités.`,
    faqDirectA: (c) => c.directB === 'all-direct' ? 'Oui, les options observées sont directes.' : c.directB === 'connections-only' ? 'Aucune option directe n’est actuellement observée.' : 'Oui, des options directes sont disponibles en plus des vols avec escale.',
    faqAirlinesA: (c) => `${c.airlineCount || 'Plusieurs'} compagnies apparaissent dans les données disponibles.`, faqDurationA: (c) => c.fmtDur ? `La durée moyenne observée est d’environ ${c.fmtDur}. La durée réelle dépend de l’itinéraire choisi.` : 'La durée dépend de l’itinéraire et des correspondances.'
  },
  es: {
    overview: 'Resumen de la ruta', price: 'Precios y momento de compra', airlines: 'Aerolíneas disponibles', direct: 'Vuelos directos y escalas', airport: 'Aeropuertos', plan: 'Cómo preparar el viaje', faqPrice: '¿Cuánto cuesta la ruta?', faqDirect: '¿Hay vuelos directos?', faqAirlines: '¿Qué aerolíneas operan la ruta?', faqDuration: '¿Cuánto dura el vuelo?',
    title: (c) => `Vuelos ${c.o} → ${c.d}: precios, aerolíneas y duración | Airpiv`,
    meta: (c) => `Compara vuelos de ${c.o} a ${c.d} con datos reales de la ruta: precios, aerolíneas, duración y opciones directas.`,
    intro: (c) => `Viajar de ${c.o} a ${c.d} no consiste solo en encontrar el precio más bajo. La duración, los horarios, las aerolíneas y las opciones sin escalas pueden cambiar cuál es la mejor elección. Aquí reunimos los datos de la ruta para comparar con criterio.`,
    overviewBody: (c) => `${c.o} y ${c.d} están a unos ${c.km} km en línea recta. La ruta se clasifica como ${c.haul}. ${c.fmtDur ? `La duración observada ronda ${c.fmtDur}. ` : ''}${c.airlineCount ? `Se han observado ${c.airlineCount} aerolíneas. ` : ''}Comprueba siempre la disponibilidad para tus fechas.`,
    priceBody: (c) => `Los precios observados parten de unos ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR${c.priceMax && c.priceMax > c.priceMin ? ` y llegan aproximadamente a ${Math.round(c.priceMax)} EUR` : ''}. ${c.priceTrend === 'up' ? 'La tendencia reciente ha sido al alza.' : c.priceTrend === 'down' ? 'La tendencia reciente ha sido a la baja.' : 'Los precios recientes han sido relativamente estables.'} El precio final depende de la fecha y las condiciones del billete.`,
    airlinesBody: (c) => `${c.airlineCount || 'Varias'} aerolíneas aparecen en los datos de la ruta. Compara horarios, equipaje y condiciones además del precio inicial para conocer el coste real del viaje.`,
    directBody: (c) => c.directB === 'all-direct' ? `Todas las opciones observadas son vuelos directos. Esto reduce el tiempo de viaje y elimina el riesgo de perder una conexión.` : c.directB === 'connections-only' ? `Los datos observados no muestran una opción directa. Deja margen suficiente para la conexión y revisa el aeropuerto de escala.` : `Hay opciones directas y vuelos con escala. El directo ahorra tiempo, mientras que una escala puede ampliar la oferta de horarios y precios.`,
    airportBody: (c) => `${c.o} sale desde ${c.oIata || 'su aeropuerto de origen'} y ${c.d} llega a ${c.dIata || 'su aeropuerto de destino'}. Comprueba la terminal y el transporte terrestre antes de viajar.`,
    planBody: (c) => `Para comparar bien, considera el tiempo total, el equipaje, los horarios y la duración de las conexiones. ${c.haul === 'long-haul' ? 'En rutas largas, el confort y la calidad de la conexión son especialmente importantes.' : 'En rutas cortas, el horario y el acceso al aeropuerto pueden ser más importantes que una pequeña diferencia de precio.'}`,
    faqPriceA: (c) => `Los precios observados parten de unos ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR, aunque el precio exacto cambia según fecha y disponibilidad.`, faqDirectA: (c) => c.directB === 'all-direct' ? 'Sí. Las opciones observadas son directas.' : c.directB === 'connections-only' ? 'No aparece una opción directa en los datos observados.' : 'Sí. Hay opciones directas además de vuelos con escala.', faqAirlinesA: (c) => `Los datos muestran ${c.airlineCount || 'varias'} aerolíneas.`, faqDurationA: (c) => c.fmtDur ? `La duración media observada es de unos ${c.fmtDur}. El tiempo real depende del itinerario.` : 'La duración depende del itinerario y de las conexiones.'
  },
  it: {
    overview: 'Panoramica della rotta', price: 'Prezzi e momento della prenotazione', airlines: 'Compagnie aeree', direct: 'Voli diretti e scali', airport: 'Aeroporti', plan: 'Come organizzare il viaggio', faqPrice: 'Quanto costa la rotta?', faqDirect: 'Ci sono voli diretti?', faqAirlines: 'Quali compagnie operano la rotta?', faqDuration: 'Quanto dura il volo?',
    title: (c) => `Voli ${c.o} → ${c.d}: prezzi, compagnie e durata | Airpiv`, meta: (c) => `Confronta i voli ${c.o}–${c.d} con dati reali: prezzi, compagnie, durata e opzioni dirette.`,
    intro: (c) => `Per volare da ${c.o} a ${c.d}, il prezzo è solo uno dei fattori. Durata, orari, compagnie e possibilità di volare senza scalo possono cambiare la scelta migliore. Questa pagina riunisce i dati della rotta per aiutarti a confrontare le opzioni prima della prenotazione.`,
    overviewBody: (c) => `${c.o} e ${c.d} distano circa ${c.km} km in linea d’aria. La rotta è classificata come ${c.haul}. ${c.fmtDur ? `La durata osservata è di circa ${c.fmtDur}. ` : ''}${c.airlineCount ? `Sono state osservate ${c.airlineCount} compagnie. ` : ''}Controlla sempre la disponibilità per le tue date.`,
    priceBody: (c) => `Le tariffe osservate partono da circa ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR${c.priceMax && c.priceMax > c.priceMin ? ` e arrivano a circa ${Math.round(c.priceMax)} EUR` : ''}. ${c.priceTrend === 'up' ? 'La tendenza recente è stata al rialzo.' : c.priceTrend === 'down' ? 'La tendenza recente è stata al ribasso.' : 'I prezzi recenti sono rimasti abbastanza stabili.'} Il prezzo finale dipende da data e condizioni del biglietto.`,
    airlinesBody: (c) => `${c.airlineCount || 'Diverse'} compagnie compaiono nei dati della rotta. Confronta orari, bagagli e condizioni oltre al prezzo iniziale.`,
    directBody: (c) => c.directB === 'all-direct' ? 'Tutte le opzioni osservate sono dirette, senza scali.' : c.directB === 'connections-only' ? 'I dati osservati non mostrano voli diretti; considera un margine adeguato per la coincidenza.' : 'Sono disponibili sia voli diretti sia itinerari con scalo. Il diretto riduce il tempo, mentre lo scalo può aumentare la scelta.',
    airportBody: (c) => `${c.o} parte da ${c.oIata || 'l’aeroporto di origine'} e ${c.d} arriva a ${c.dIata || 'l’aeroporto di destinazione'}. Controlla terminal e collegamenti prima della partenza.`,
    planBody: (c) => `Confronta durata complessiva, bagagli, orari e tempi di coincidenza. ${c.haul === 'long-haul' ? 'Sulle rotte lunghe, comfort e qualità dello scalo diventano particolarmente importanti.' : 'Sulle rotte brevi, orari e accessibilità dell’aeroporto possono contare più di una piccola differenza di prezzo.'}`,
    faqPriceA: (c) => `Le tariffe osservate partono da circa ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR, ma il prezzo esatto varia in base a data e disponibilità.`, faqDirectA: (c) => c.directB === 'all-direct' ? 'Sì, le opzioni osservate sono dirette.' : c.directB === 'connections-only' ? 'Non è presente un’opzione diretta nei dati osservati.' : 'Sì, sono presenti opzioni dirette oltre ai voli con scalo.', faqAirlinesA: (c) => `Nei dati disponibili compaiono ${c.airlineCount || 'diverse'} compagnie.`, faqDurationA: (c) => c.fmtDur ? `La durata media osservata è di circa ${c.fmtDur}. La durata effettiva dipende dall’itinerario.` : 'La durata dipende dall’itinerario e dalle coincidenze.'
  },
  nl: {
    overview: 'Overzicht van de route', price: 'Prijs en boekmoment', airlines: 'Luchtvaartmaatschappijen', direct: 'Rechtstreekse vluchten en overstappen', airport: 'Luchthavens', plan: 'De reis goed plannen', faqPrice: 'Wat kost de route?', faqDirect: 'Zijn er rechtstreekse vluchten?', faqAirlines: 'Welke luchtvaartmaatschappijen vliegen deze route?', faqDuration: 'Hoe lang duurt de vlucht?',
    title: (c) => `Vluchten ${c.o} → ${c.d}: prijzen, airlines en vliegtijd | Airpiv`, meta: (c) => `Vergelijk vluchten van ${c.o} naar ${c.d} met echte routegegevens: prijzen, airlines, vliegtijd en directe opties.`,
    intro: (c) => `Een goede vlucht van ${c.o} naar ${c.d} draait niet alleen om de laagste prijs. Vliegtijd, vertrektijd, luchtvaartmaatschappij en directe opties bepalen samen wat praktisch het beste ticket is. Deze pagina brengt de beschikbare routegegevens overzichtelijk bij elkaar.`,
    overviewBody: (c) => `${c.o} en ${c.d} liggen ongeveer ${c.km} km van elkaar. De route valt onder ${c.haul}. ${c.fmtDur ? `De waargenomen vliegtijd ligt rond ${c.fmtDur}. ` : ''}${c.airlineCount ? `Er zijn ${c.airlineCount} airlines waargenomen. ` : ''}Controleer de actuele beschikbaarheid voor jouw reisdatum.`,
    priceBody: (c) => `Waargenomen tarieven beginnen rond ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR${c.priceMax && c.priceMax > c.priceMin ? ` en lopen op tot ongeveer ${Math.round(c.priceMax)} EUR` : ''}. ${c.priceTrend === 'up' ? 'De recente trend was stijgend.' : c.priceTrend === 'down' ? 'De recente trend was dalend.' : 'De recente prijzen waren redelijk stabiel.'} Het uiteindelijke tarief hangt af van datum en ticketvoorwaarden.`,
    airlinesBody: (c) => `${c.airlineCount || 'Meerdere'} airlines komen voor in de routegegevens. Vergelijk naast de prijs ook vertrektijden, bagage en wijzigingsvoorwaarden.`,
    directBody: (c) => c.directB === 'all-direct' ? 'Alle waargenomen opties zijn rechtstreeks. Dat maakt de route eenvoudig en voorspelbaar.' : c.directB === 'connections-only' ? 'In de waargenomen gegevens staat geen directe optie. Plan extra tijd voor de overstap.' : 'Er zijn zowel directe vluchten als opties met overstap. Direct is sneller; een overstap kan meer keuze geven.',
    airportBody: (c) => `${c.o} vertrekt via ${c.oIata || 'de luchthaven van vertrek'} en ${c.d} via ${c.dIata || 'de luchthaven van aankomst'}. Controleer terminal en vervoer naar de luchthaven voor vertrek.`,
    planBody: (c) => `Vergelijk totale reistijd, bagage, vertrektijden en overstaptijd. ${c.haul === 'long-haul' ? 'Bij lange vluchten zijn comfort en een goede overstap extra belangrijk.' : 'Bij kortere routes kunnen vertrektijd en bereikbaarheid van de luchthaven belangrijker zijn dan een klein prijsverschil.'}`,
    faqPriceA: (c) => `Waargenomen prijzen beginnen rond ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR. Het exacte tarief verschilt per datum en beschikbaarheid.`, faqDirectA: (c) => c.directB === 'all-direct' ? 'Ja, de waargenomen opties zijn rechtstreeks.' : c.directB === 'connections-only' ? 'Er staat momenteel geen directe optie in de waargenomen gegevens.' : 'Ja, er zijn directe opties naast vluchten met overstap.', faqAirlinesA: (c) => `De beschikbare gegevens tonen ${c.airlineCount || 'meerdere'} airlines.`, faqDurationA: (c) => c.fmtDur ? `De gemiddelde waargenomen vliegtijd is ongeveer ${c.fmtDur}. De werkelijke reistijd hangt af van het ticket.` : 'De reistijd hangt af van route en eventuele overstappen.'
  },
  pl: {
    overview: 'Przegląd trasy', price: 'Ceny i moment rezerwacji', airlines: 'Linie lotnicze', direct: 'Loty bezpośrednie i przesiadki', airport: 'Lotniska', plan: 'Jak zaplanować podróż', faqPrice: 'Ile kosztuje ta trasa?', faqDirect: 'Czy są loty bezpośrednie?', faqAirlines: 'Jakie linie obsługują trasę?', faqDuration: 'Ile trwa lot?',
    title: (c) => `Loty ${c.o} → ${c.d}: ceny, linie i czas lotu | Airpiv`, meta: (c) => `Porównaj loty ${c.o}–${c.d} na podstawie danych trasy: ceny, linie lotnicze, czas lotu i opcje bezpośrednie.`,
    intro: (c) => `Wybór lotu z ${c.o} do ${c.d} zależy nie tylko od ceny. Czas podróży, godzina wylotu, linia lotnicza i możliwość lotu bezpośredniego mogą być równie ważne. Ta strona zbiera dostępne dane trasy, aby ułatwić rozsądne porównanie przed rezerwacją.`,
    overviewBody: (c) => `${c.o} i ${c.d} dzieli około ${c.km} km w linii prostej. Trasa jest klasyfikowana jako ${c.haul}. ${c.fmtDur ? `Obserwowany czas lotu to około ${c.fmtDur}. ` : ''}${c.airlineCount ? `Na trasie zaobserwowano ${c.airlineCount} linii lotniczych. ` : ''}Sprawdź aktualną dostępność dla swoich dat.`,
    priceBody: (c) => `Obserwowane ceny zaczynają się od około ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR${c.priceMax && c.priceMax > c.priceMin ? ` i sięgają około ${Math.round(c.priceMax)} EUR` : ''}. ${c.priceTrend === 'up' ? 'Ostatni trend cenowy był wzrostowy.' : c.priceTrend === 'down' ? 'Ostatni trend cenowy był spadkowy.' : 'Ceny były ostatnio stosunkowo stabilne.'} Cena końcowa zależy od daty i warunków biletu.`,
    airlinesBody: (c) => `${c.airlineCount || 'Kilka'} linii lotniczych występuje w danych trasy. Porównuj także godziny, bagaż i zasady zmian, a nie tylko cenę podstawową.`,
    directBody: (c) => c.directB === 'all-direct' ? 'Wszystkie obserwowane opcje są bezpośrednie, więc nie trzeba planować przesiadki.' : c.directB === 'connections-only' ? 'W obserwowanych danych nie ma lotu bezpośredniego. Zaplanuj odpowiedni zapas czasu na przesiadkę.' : 'Dostępne są zarówno loty bezpośrednie, jak i z przesiadką. Lot bezpośredni oszczędza czas, a przesiadka może zwiększyć wybór.',
    airportBody: (c) => `${c.o} korzysta z ${c.oIata || 'lotniska wylotu'}, a ${c.d} z ${c.dIata || 'lotniska docelowego'}. Przed podróżą sprawdź terminal i transport na lotnisko.`,
    planBody: (c) => `Porównaj całkowity czas podróży, bagaż, godziny wylotu i czas przesiadki. ${c.haul === 'long-haul' ? 'Na długich trasach komfort i jakość przesiadki mają szczególne znaczenie.' : 'Na krótszych trasach wygodny rozkład i dojazd na lotnisko mogą być ważniejsze niż niewielka różnica ceny.'}`,
    faqPriceA: (c) => `Obserwowane ceny zaczynają się od około ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR, ale dokładna cena zależy od daty i dostępności.`, faqDirectA: (c) => c.directB === 'all-direct' ? 'Tak, obserwowane opcje są bezpośrednie.' : c.directB === 'connections-only' ? 'W obserwowanych danych nie ma obecnie opcji bezpośredniej.' : 'Tak, dostępne są opcje bezpośrednie oraz loty z przesiadką.', faqAirlinesA: (c) => `Dane pokazują ${c.airlineCount || 'kilka'} linii lotniczych.`, faqDurationA: (c) => c.fmtDur ? `Średni obserwowany czas lotu to około ${c.fmtDur}. Rzeczywisty czas zależy od wybranego połączenia.` : 'Czas podróży zależy od połączenia i przesiadek.'
  },
  tr: {
    overview: 'Rota özeti', price: 'Fiyatlar ve rezervasyon zamanı', airlines: 'Havayolları', direct: 'Direkt uçuşlar ve aktarmalar', airport: 'Havalimanları', plan: 'Seyahati planlama', faqPrice: 'Bu rota ne kadar tutar?', faqDirect: 'Direkt uçuş var mı?', faqAirlines: 'Hangi havayolları uçuyor?', faqDuration: 'Uçuş ne kadar sürüyor?',
    title: (c) => `${c.o} → ${c.d} uçuşları: fiyatlar, havayolları ve uçuş süresi | Airpiv`, meta: (c) => `${c.o}–${c.d} uçuşlarını gerçek rota verileriyle karşılaştırın: fiyatlar, havayolları, uçuş süresi ve direkt seçenekler.`,
    intro: (c) => `${c.o} ile ${c.d} arasında doğru uçuşu seçmek yalnızca en düşük fiyatı bulmak değildir. Uçuş süresi, saatler, havayolu ve direkt seçenekler toplam seyahat deneyimini değiştirir. Bu sayfa, rezervasyondan önce önemli rota verilerini tek yerde karşılaştırmanıza yardımcı olur.`,
    overviewBody: (c) => `${c.o} ve ${c.d} arasında kuş uçuşu yaklaşık ${c.km} km vardır. Rota ${c.haul} olarak sınıflandırılır. ${c.fmtDur ? `Gözlemlenen uçuş süresi yaklaşık ${c.fmtDur}. ` : ''}${c.airlineCount ? `${c.airlineCount} havayolu gözlemlendi. ` : ''}Seyahat tarihiniz için güncel uygunluğu ayrıca kontrol edin.`,
    priceBody: (c) => `Gözlemlenen fiyatlar yaklaşık ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR seviyesinden başlıyor${c.priceMax && c.priceMax > c.priceMin ? ` ve yaklaşık ${Math.round(c.priceMax)} EUR seviyesine çıkıyor` : ''}. ${c.priceTrend === 'up' ? 'Son dönemde fiyat eğilimi yükseliş yönünde.' : c.priceTrend === 'down' ? 'Son dönemde fiyat eğilimi düşüş yönünde.' : 'Son dönemde fiyatlar nispeten istikrarlı.'} Nihai fiyat tarih ve bilet koşullarına göre değişir.`,
    airlinesBody: (c) => `Rota verilerinde ${c.airlineCount || 'birden fazla'} havayolu yer alıyor. Sadece temel ücreti değil; saatleri, bagajı ve değişiklik koşullarını da karşılaştırın.`,
    directBody: (c) => c.directB === 'all-direct' ? 'Gözlemlenen seçeneklerin tamamı direkt uçuş. Böylece aktarma planlamaya gerek kalmıyor.' : c.directB === 'connections-only' ? 'Gözlemlenen verilerde direkt uçuş bulunmuyor. Aktarma için yeterli zaman bırakın.' : 'Hem direkt hem aktarmalı seçenekler bulunuyor. Direkt uçuş zaman kazandırırken aktarma daha fazla seçenek sunabilir.',
    airportBody: (c) => `${c.o}, ${c.oIata || 'kalkış havalimanı'} üzerinden; ${c.d} ise ${c.dIata || 'varış havalimanı'} üzerinden hizmet veriyor. Terminal ve havalimanı ulaşımını kalkıştan önce kontrol edin.`,
    planBody: (c) => `Toplam seyahat süresini, bagajı, kalkış saatini ve aktarma süresini karşılaştırın. ${c.haul === 'long-haul' ? 'Uzun mesafeli rotalarda konfor ve aktarma kalitesi özellikle önemlidir.' : 'Kısa rotalarda uygun saatler ve havalimanına ulaşım, küçük bir fiyat farkından daha önemli olabilir.'}`,
    faqPriceA: (c) => `Gözlemlenen fiyatlar yaklaşık ${c.priceMin != null ? Math.round(c.priceMin) : '—'} EUR seviyesinden başlıyor; kesin fiyat tarih ve müsaitliğe göre değişir.`, faqDirectA: (c) => c.directB === 'all-direct' ? 'Evet, gözlemlenen seçenekler direkt.' : c.directB === 'connections-only' ? 'Gözlemlenen verilerde şu anda direkt seçenek yok.' : 'Evet, aktarmalı uçuşların yanında direkt seçenekler de bulunuyor.', faqAirlinesA: (c) => `Mevcut veriler ${c.airlineCount || 'birden fazla'} havayolunu gösteriyor.`, faqDurationA: (c) => c.fmtDur ? `Gözlemlenen ortalama uçuş süresi yaklaşık ${c.fmtDur}. Gerçek süre seçilen güzergâha göre değişir.` : 'Süre, seçilen güzergâh ve aktarmalara göre değişir.'
  }
};

function makePack(language) {
  const l = LOCALES[language];
  if (!l) return null;
  const section = (heading, body) => ({ heading, body, applicable: () => true, weight: () => 0.7, render: (c) => ({ heading, body: body(c) }) });
  return {
    INTRO_ANGLES: { traveler: [l.intro], price: [l.intro], duration: [l.intro], airline: [l.intro], airport: [l.intro], business: [l.intro], family: [l.intro], weekend: [l.intro], seasonal: [l.intro], destination: [l.intro] },
    TITLES: [l.title], METAS: [l.meta],
    BLOCKS: [
      section(l.overview, l.overviewBody), section(l.price, l.priceBody), section(l.airlines, l.airlinesBody),
      section(l.direct, l.directBody), section(l.airport, l.airportBody), section(l.plan, l.planBody)
    ],
    FAQ_CANDIDATES: [
      { id: 'price-from', applicable: () => true, q: () => l.faqPrice, a: l.faqPriceA },
      { id: 'direct', applicable: () => true, q: () => l.faqDirect, a: l.faqDirectA },
      { id: 'airlines', applicable: () => true, q: () => l.faqAirlines, a: l.faqAirlinesA },
      { id: 'duration', applicable: () => true, q: () => l.faqDuration, a: l.faqDurationA }
    ]
  };
}

module.exports = { makePack, LOCALES, languages: Object.keys(LOCALES) };
