// ═══════════════════════════════════════════════════════════════════════════
// src/services/seoBatchProcessor.js
// Batch-applies quality-gated SEO content to published route pages.
//
// Guarantees (enforced together with seoContentEngine.js):
//   • Manually written content is never overwritten — a route with ANY hand-
//     edited field is skipped whole, not partially filled.
//   • Routes without enough real data (distance, cities, haul type) are skipped
//     rather than filled with generic filler — "prefer no content over
//     low-quality content".
//   • Every page differs: the engine seeds variant selection from the slug.
// ═══════════════════════════════════════════════════════════════════════════

const supa = require('../clients/supabase');
const log = require('../utils/log');
const {
  generateRouteContent,
  assessRouteEligibility,
  hasManualContent,
  supportedLanguages,
} = require('./seoContentEngine');

const BATCH_SIZE = 50;
// Primary language written into the shared route_pages columns. Additional
// languages are generated by the engine but stored elsewhere (see note in
// updateRoutePageSEO) — the base row carries the platform's primary market
// language, German.
const PRIMARY_LANGUAGE = 'de';

async function fetchRoutePagesForUpdate() {
  if (!supa) throw new Error('Database not available');
  const { data, error } = await supa
    .from('route_pages')
    .select('*')
    .eq('status', 'published')
    .order('created_at', { ascending: false });
  if (error) throw new Error(error.message);
  return data || [];
}

async function fetchCitiesForUpdate() {
  if (!supa) throw new Error('Database not available');
  const { data, error } = await supa.from('cities').select('*').eq('status', 'published');
  if (error) throw new Error(error.message);
  return data || [];
}

async function fetchCountriesForUpdate() {
  if (!supa) throw new Error('Database not available');
  const { data, error } = await supa.from('countries').select('*').eq('status', 'published');
  if (error) throw new Error(error.message);
  return data || [];
}

// Writes generated content into the route's empty SEO columns. Because the gate
// already rejected any route with manual content, every target field here is
// known-empty; the per-field guard is a belt-and-braces second check so a
// concurrent manual edit between fetch and write can never be clobbered.
async function updateRoutePageSEO(route, content, { dryRun = false } = {}) {
  const updateData = {};
  if (!route.custom_title) updateData.custom_title = content.title;
  if (!route.custom_meta_description) updateData.custom_meta_description = content.metaDescription;
  if (!route.custom_faq || (Array.isArray(route.custom_faq) && !route.custom_faq.length)) {
    updateData.custom_faq = content.faq;
  }
  if (!route.intro_text) updateData.intro_text = content.intro;

  if (Object.keys(updateData).length === 0) return { updated: false };
  if (dryRun) return { updated: true, preview: updateData };

  const { error } = await supa.from('route_pages').update(updateData).eq('id', route.id);
  if (error) {
    log('warn', 'route_seo_update_failed', { route_id: route.id, error: error.message });
    return { updated: false, error: error.message };
  }
  return { updated: true };
}

async function processRoutes(progressCallback, { dryRun = false } = {}) {
  const routes = await fetchRoutePagesForUpdate();
  const total = routes.length;
  let processed = 0, updated = 0, skipped = 0, failed = 0;
  const skipReasons = {};

  log('info', 'seo_batch_start', { total, dryRun, primary_language: PRIMARY_LANGUAGE });

  for (let i = 0; i < routes.length; i += BATCH_SIZE) {
    const batch = routes.slice(i, i + BATCH_SIZE);
    for (const route of batch) {
      processed++;
      try {
        const result = generateRouteContent(route, PRIMARY_LANGUAGE);
        if (result.skipped) {
          skipped++;
          for (const r of result.reasons) skipReasons[r] = (skipReasons[r] || 0) + 1;
        } else {
          const writeRes = await updateRoutePageSEO(route, result.content, { dryRun });
          if (writeRes.error) failed++;
          else if (writeRes.updated) updated++;
          else skipped++;
        }
      } catch (err) {
        failed++;
        log('warn', 'route_processing_error', { route: route.id, error: err.message });
      }
      if (progressCallback) {
        progressCallback({ processed, total, updated, skipped, failed,
          current: `${route.origin_city} → ${route.destination_city}` });
      }
    }
    if (!dryRun) await new Promise((r) => setTimeout(r, 100));
  }

  const summary = { total, processed, updated, skipped, failed, skipReasons, dryRun };
  log('info', 'seo_batch_complete', summary);
  return summary;
}

async function processSingleRoute(routeId, language = PRIMARY_LANGUAGE, { dryRun = false } = {}) {
  if (!supa) throw new Error('Database not available');
  const { data: route, error } = await supa.from('route_pages').select('*').eq('id', routeId).maybeSingle();
  if (error) throw new Error(error.message);
  if (!route) throw new Error(`Route ${routeId} not found`);

  const result = generateRouteContent(route, language);
  if (result.skipped) {
    log('info', 'single_route_skipped', { route_id: routeId, reasons: result.reasons });
    return { skipped: true, reasons: result.reasons };
  }
  const writeRes = await updateRoutePageSEO(route, result.content, { dryRun });
  log('info', 'single_route_seo_generated', { route_id: routeId, language, dryRun, updated: writeRes.updated });
  return { skipped: false, content: result.content, ...writeRes };
}

// Readiness report: how many routes are eligible vs. why the rest are skipped.
async function generateStatistics() {
  const routes = await fetchRoutePagesForUpdate();
  let eligible = 0, manual = 0, insufficientData = 0;
  const reasonCounts = {};
  for (const route of routes) {
    const gate = assessRouteEligibility(route);
    if (gate.eligible) { eligible++; continue; }
    if (hasManualContent(route)) manual++;
    else insufficientData++;
    for (const r of gate.reasons) reasonCounts[r] = (reasonCounts[r] || 0) + 1;
  }
  return {
    total_published_routes: routes.length,
    eligible_for_generation: eligible,
    skipped_manual_content: manual,
    skipped_insufficient_data: insufficientData,
    skip_reason_breakdown: reasonCounts,
    languages_supported: supportedLanguages(),
  };
}

module.exports = {
  processRoutes,
  processSingleRoute,
  generateStatistics,
  fetchRoutePagesForUpdate,
  fetchCitiesForUpdate,
  fetchCountriesForUpdate,
  updateRoutePageSEO,
  BATCH_SIZE,
  PRIMARY_LANGUAGE,
};
